server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



spring:
  profiles:
    include: db, file, oauth
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 811925032263-j0fal4gourtfct5aiihvrb9mgsi51fc5.apps.googleusercontent.com
            clientSecret: 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
            scope: profile,email
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:server
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    username: haribo  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password: 6002 # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

#file:
#  profileImg: ProfileImg/
#  boardImg: BoardImg/
#  itineraryImg: ItineraryImg/

iam:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

env: server
logTracer: false

jwt:
  secret:
    key: 123123123123123123123123123123123123123123123123123123123123123213213213123123123123123
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420